version: '3.1'
services:
  artifactory:
    container_name: artifactory
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    networks:
      - "tools"
    ports:
      - 8081:8081
      - 8082:8082
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
    volumes:
      - "./storage/artifactory/var:/var/opt/jfrog/artifactory"
  jenkins:
    container_name: jenkins
    depends_on:
      - postgres
    image: jenkins/jenkins:latest
    networks:
      - "tools"
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - "./storage/jenkins/home:/var/jenkins_home"
  sonarqube:
    container_name: sonarqube
    depends_on:
      - postgres
    environment:
      SONAR_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
      SONAR_JDBC_USERNAME: "sonar"
      SONAR_JDBC_PASSWORD: "sonar"
    image: sonarqube:latest
    networks:
      - "tools"
    ports:
      - 9000:9000
    volumes:
      - "./storage/sonarqube/data:/opt/sonarqube/data"
      - "./storage/sonarqube/logs:/opt/sonarqube/logs"
      - "./storage/sonarqube/extensions:/opt/sonarqube/extensions"
  postgres:
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    image: postgres:latest
    networks:
      - "tools"
    # ports:
    #   - 5432:5432
    volumes:
      - "./postgres-initdb.sql:/docker-entrypoint-initdb.d/init.sql"
      - "./storage/postgres/data:/var/lib/postgresql/data"
networks:
  tools: